# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Artists Theme
email: your-email@domain.com
description: designer // thinker // youTuber
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

bg-img: hero-bg.jpg
logo: logo.svg
avatar: travitar.jpg
blurb: <p><strong>Lorem ipsum dolor sit amet</strong>, consectetur adipisicing elit. Architecto aspernatur autem commodi cumque deleniti dolore doloremque eaque eligendi esse est fugit hic id ipsum itaque molestiae nemo nobis non nostrum, omnis quam qui quibusdam saepe sapiente, vel velit vero voluptatibus.
       </p>

# Build settings
markdown: kramdown

port: 8080
sass:
  sass_dir: assets/css
  style: :nested

